library(tidyverse)
library(stringr)
library(readr)
country_vaccinations <- read_csv("country_vaccinations.csv")
library(dplyr)
library(magrittr)
library(ggplot2)
most_vaccinated<-country_vaccinations %>% filter(!is.na(people_vaccinated))  %>% select(country,date,people_vaccinated) %>% arrange(desc(people_vaccinated)) %>% distinct(country,`.keep_all` = TRUE)
major_vaccinated<-most_vaccinated %>% arrange(desc(people_vaccinated) ) %>% head(10) %>%ggplot()+geom_col(mapping = aes(x = reorder(country,desc(people_vaccinated)),y =people_vaccinated, fill=country ), show.legend = FALSE)+coord_flip()+theme_light()+ggtitle(label = "Most vaccinated countries.")+xlab(label = "Countries")+ylab(label = "millions")
major_vaccinated
country_vaccinations %>% group_by(country,vaccines) %>% distinct(country,vaccines)
por_percentage<-country_vaccinations %>% filter(!is.na(people_fully_vaccinated_per_hundred)) %>% select(country,date,people_fully_vaccinated_per_hundred) %>% arrange(desc(people_fully_vaccinated_per_hundred)) %>% distinct(country,`.keep_all` = TRUE)
major_percentage<-por_percentage %>% arrange(desc(people_fully_vaccinated_per_hundred)) %>% head(10) %>%ggplot()+geom_col(mapping = aes(x= reorder(country,desc(people_fully_vaccinated_per_hundred)),y = people_fully_vaccinated_per_hundred),fill="#1E90FF")+coord_flip()+  theme_light()+ggtitle(label = "Proportional to the population.")+geom_text(aes(x = country,y =people_fully_vaccinated_per_hundred,label=people_fully_vaccinated_per_hundred ),hjust=-0.5)+xlab(label = "Countries ")+ylab(label = "Percentage")+scale_y_continuous(limits = c(0,50),breaks = c(0,20,40))
major_percentage
library(gridExtra)
grid.arrange(major_vaccinated ,major_percentage)
install.packages("cartography")
install.packages("rgdal")
install.packages("sp")
library("cartography")
library("rgdal")
library("sp")
install.packages('rworldmap',dependencies=TRUE) 

